name: pipelinePy

on: push

env:
   FILE_NAME: hello-world

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout the code
          uses: actions/checkout@v2

        - name: Test
          uses: fedora-python/tox-github-action@v39.0
          with:
              file: ${{env.FILE_NAME}}
              path: ./${{env.FILE_NAME}}.py
